---
title: "Chapter 2"
output: html_document
---

```{r load_tidyverse_rwr}
library(tidyverse)
library(rwr)
```

## the `sw` Dataset

```{r sw, paged.print=FALSE}
sw
```

## filter: Picking Observations by their Values

```{r sw_filter_droid, paged.print=FALSE}
filter(sw, species == "Droid")
```


```{r sw_filter_height_gt_220, paged.print=FALSE}
filter(sw, height > 220)
```


```{r sw_height_mass, paged.print=FALSE}
# Filter characters by either `height` above 210, or, `mass` above 120
filter(sw, height > 210 | mass > 120)
```


```{r sw_species_or, paged.print=FALSE}
# Get all Droid and Human characters; method 1 with [expr | expr]
filter(sw, species == "Droid" | species == "Human")
```


```{r sw_species_in, paged.print=FALSE}
# Get all Droid and Human characters; method 2 with [colname %in% c(...)]
filter(sw, species %in% c("Droid", "Human"))
```


```{r sw_arrange_height, paged.print=FALSE}
# Arrange characters by increasing height
arrange(sw, height)
```


```{r sw_arrange_twice, paged.print=FALSE}
# Arrange characters by hair color and then by gender
arrange(sw, hair_color, gender)
```


```{r sw_arrange_twice_desc, paged.print=FALSE}
# Arrange by descending `hair_color`, then by ascending `gender`
arrange(sw, desc(hair_color), gender)
```


## select: Picking Variables by their Names

```{r sw_select, paged.print=FALSE}
# Select the `name`, `gender`, and `species` columns
select(sw, name, gender, species)
```


```{r sw_select_revised, paged.print=FALSE}
# Select the `gender`, `species`, and `name` columns; in that order
select(sw, gender, species, name)
```


```{r sw_select_starts_with, paged.print=FALSE}
# Select `name` and any columns starting with "h" 
select(sw, name, starts_with("h"))
```


```{r sw_select_ends_with, paged.print=FALSE}
# Select `name` and any columns ending with "s" 
select(sw, name, ends_with("s"))
```


```{r sw_select_contains, paged.print=FALSE}
# Select `name` and all other columns containing a `_` character 
select(sw, name, contains("_"))
```


```{r sw_select_w_everything, paged.print=FALSE}
# Put 3 specific columns first then everything else after that 
select(sw, name, homeworld, gender, everything())
```


## mutate: Creating New Variables with Expressions

```{r make_sw_smaller, paged.print=FALSE}
# Create the `starwars_small` table, containing just 3 columns
sw_small <- select(sw, name, height, mass)
sw_small
```


```{r mutate_bmi, paged.print=FALSE}
# Add the `bmi` column containing a calculation based
# on `height` and `mass` (with units of kg/m^2)
mutate(sw_small, bmi = mass / (height / 100)^2)
```


```{r mutate_bmi_round, paged.print=FALSE}
# Add the `bmi` column as before and then create `bmi_rnd`
mutate(
  sw_small,
  bmi = mass / (height / 100)^2,
  bmi_rnd = round(bmi, 0)
)
```


## summarize: Collapsing Many Values Down to a Single Summary

```{r group_by_summarize_mean, paged.print=FALSE}
# Create grouped data; where the table is grouped by `species`
by_species <- group_by(sw, species)

# Create a data summary that gets the mean mass by `species`
summarize(by_species, avg_mass = mean(mass))
```


```{r group_by_summarize_mean_na_rm, paged.print=FALSE}
# Create grouped data; where the table is grouped by `species`
by_species <- group_by(sw, species)

# Summarize with means, removing NA values
summarize(by_species, avg_mass = mean(mass, na.rm = TRUE))
```


```{r sw_summarize_two_column_groups, paged.print=FALSE}
# Create grouped data; grouping by `species` and `gender`
grouping <- group_by(sw, species, gender)

# Summarize to get average mass and average height
summarize(
  grouping,
  avg_mass = mean(mass, na.rm = TRUE),
  avg_height = mean(height, na.rm = TRUE)
)
```


## Bringing All of This Together with the Pipe (%>%)

```{r dplyr_stmts, paged.print=FALSE}
# Get average BMI values for humans across the different worlds

humans <- filter(sw, species == "Human")

humans_bmi <- mutate(humans, bmi = mass / (height / 100)^2)

humans_bmi_by_homeworld <- group_by(humans_bmi, homeworld)

humans_avg_bmi_by_homeworld <- 
  summarize(humans_bmi_by_homeworld, avg_bmi = mean(bmi, na.rm = TRUE))

humans_avg_bmi_by_homeworld_sorted <-
  arrange(humans_avg_bmi_by_homeworld, desc(avg_bmi))

humans_avg_bmi_by_homeworld_sorted
```


```{r dplyr_piped, paged.print=FALSE}
# Get a table of average BMI values for humans across
# the different worlds in a single, piped expression
bmi_sorted <- 
  sw %>%
  filter(species == "Human") %>%
  mutate(bmi = mass / (height / 100)^2) %>%
  group_by(homeworld) %>%
  summarize(avg_bmi = mean(bmi, na.rm = TRUE)) %>%
  arrange(desc(avg_bmi))

bmi_sorted
```



```{r tibble_all_n}
tibble(
  a = c(3, 5, 2, 6),
  b = c("a", "b", "g", "b")
)
```


```{r tibble_n_1}
tibble(
  a = 3,
  b = c("a", "b", "g", "b")
)
```


```{r tibble_na_vals}
tibble(
  a = c(3, 5, 2, NA),
  b = c("a", NA, "g", "b")
)
```


```{r tibble_na_col}
tibble(
  a = NA,
  b = c("a", "b", "g", "b")
)
```


```{r tibble_na_character}
tibble(
  a = NA_character_,
  b = c("a", "b", "g", "b")
)
```


```{r tribble_use}
tribble(
  ~a, ~b,
  3,  "a",
  5,  "b",
  2,  "g",
  6,  "b"
)
```


```{r bind_rows_common_names}
tbl_1 <- tibble(a = c(1, 2), b = c("a", "b"))

tbl_2 <- tibble(a = c(3, 4), b = c("c", "d"))

bind_rows(tbl_1, tbl_2)
```


```{r bind_rows_uncommon_names}
tbl_1 <- tibble(a = c(1, 2), b = c("a", "b"))

tbl_2 <- tibble(c = c(3, 4), d = c("c", "d"))

bind_rows(tbl_1, tbl_2)
```


```{r bind_rows_uncommon_types, error=TRUE}
tbl_1 <- tibble(a = c("a", "b"), b = c(1, 2))

tbl_2 <- tibble(a = c(3, 4), b = c("c", "d"))

bind_rows(tbl_1, tbl_2)
```

