---
title: "Chapter 4"
output: html_document
---

```{r load_tidyverse_rwr}
library(tidyverse)
library(rwr)
```


```{r winniweather, paged.print=FALSE}
winniweather
```


```{r winni_gather, paged.print=FALSE}
winni_mod <- 
  winniweather %>%
  gather(
    key = hour,
    value = temp,
    starts_with("temp")
  )

winni_mod
```


```{r mutate_case_when, paged.print=FALSE}
winni_mod <- 
  winni_mod %>%
  mutate(hour = case_when(
    hour == "temp00_00" ~ 0L,
    hour == "temp06_00" ~ 6L,
    hour == "temp12_00" ~ 12L,
    hour == "temp18_00" ~ 18L)
  )

winni_mod
```


```{r separate, paged.print=FALSE}
winni_tidy <- 
  winni_mod %>%
  separate(
    col = yearmonth,
    into = c("year", "month"),
    sep = "-",
    convert = TRUE
  )

winni_tidy
```


```{r weather_arrange, paged.print=FALSE}
winni_tidy <- 
  winni_tidy %>%
  arrange(year, month, day, hour)

winni_tidy
```


```{r winni_iso_date, paged.print=FALSE}
winni_tidy <- 
  winni_tidy %>%
  mutate(iso_date = ISOdate(year, month, day, hour))

winni_tidy
```


```{r weather_ggplot}
ggplot(data = winniweather_iso) +
  geom_point(mapping = aes(x = iso_date, y = temp))
```
