---
title: "Chapter 3.1"
author: "rwr"
output: 
  html_document:
    df_print: paged
---

```{r load_tidyverse}
library(tidyverse)
```


## Making Simple ggplot Scatterplots

```{r gg_empty}
ggplot(data = mtcars, mapping = aes(x = wt, y = qsec))
```


```{r mtcars_wt_qsec_point}
ggplot(data = mtcars, mapping = aes(x = wt, y = qsec)) +
  geom_point()
```


```{r mtcars_wt_mpg_point}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point()
```

```{r gear_as_color_scale}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg, color = gear)) +
  geom_point()
```


```{r gear_as_factor}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg, color = factor(gear))) +
  geom_point()
```


```{r constant_blue_points}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(color = "blue")
```


```{r plot_1}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(color = factor(gear), shape = factor(cyl)))
```

```{r plot_2}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(color = factor(gear)), alpha = 0.5)
```

```{r plot_3}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(color = "black", fill = "#AAAFEF", shape = 23)
```

```{r plot_4}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(size = hp, color = qsec))
```


## Facets and the act of faceting in ggplot

```{r mtcars_facet_cyl}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point() +
  facet_wrap(facets = vars(cyl))
```



```{r mtcars_facet_am_cyl}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point() +
  facet_wrap(facets = vars(am, cyl))
```


```{r mtcars_facet_am_cyl_labeller}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(size = hp), alpha = 0.5) +
  facet_wrap(facets = vars(am, cyl), labeller = label_both)
```


```{r mtcars_facet_am_cyl_wide}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(size = hp), alpha = 0.5) +
  facet_wrap(facets = vars(am, cyl), nrow = 1, labeller = label_both)
```


```{r mtcars_facet_am_cyl_grid}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(size = hp), alpha = 0.5) +
  facet_grid(rows = vars(am), cols = vars(cyl), labeller = label_both)
```


## Working with labels and titles

```{r plot_1_new_labs}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(color = factor(gear), shape = factor(cyl))) +
  labs(
    x = "Weight (1,000s of lbs)", y = "Miles per Gallon",
    color = "Gears", shape = "Cylinders")
```


```{r plot_1_labs_titles}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(color = factor(gear), shape = factor(cyl))) +
  labs(
    title = "The Effect of Car Weight on Fuel Economy",
    subtitle = "Number of cylinders and gears indicated by shape and color",
    caption = "Data taken from the mtcars dataset in R.",
    x = "Weight (1,000s of lbs)", y = "Miles per Gallon",
    color = "Gears", shape = "Cylinders")
```


## Modifying the location of legends

```{r plot_legend_right}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(color = factor(gear), shape = factor(cyl))) +
  labs(color = "Gears", shape = "Cylinders") +
  theme(legend.position = "right")
```

```{r plot_legend_bottom}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(color = factor(gear), shape = factor(cyl))) +
  labs(color = "Gears", shape = "Cylinders") +
  theme(legend.position = "bottom")
```

```{r plot_legend_just_top}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(color = factor(gear), shape = factor(cyl))) +
  labs(color = "Gears", shape = "Cylinders") +
  theme(legend.justification = "top")
```

```{r plot_legend_none}
ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(color = factor(gear), shape = factor(cyl))) +
  labs(color = "Gears", shape = "Cylinders") +
  theme(legend.position = "none")
```


## Modifying your dataset, plotting… and modifying again.

```{r mtcars_modified_dplyr}
mtcars_mod <- mtcars %>%
  mutate(wt = wt * 1000) %>%
  mutate(am = ifelse(am == 1, "automatic", "manual"))

ggplot(data = mtcars_mod, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(size = hp), alpha = 0.5) +
  facet_wrap(facets = vars(am, cyl), labeller = label_both) +
  labs(size = "HP")
```


```{r mtcars_modified_dplyr_2}
mtcars_mod <- mtcars_mod %>%
  mutate(carb = ifelse(carb >= 4, "many", "few"))

ggplot(data = mtcars_mod, mapping = aes(x = wt, y = mpg)) +
  geom_point(mapping = aes(size = hp, shape = carb), alpha = 0.5) +
  facet_wrap(facets = vars(am, cyl), labeller = label_both) +
  labs(x = "Weight (lbs)", y = "Miles per Gallon",
       size = "HP", shape = "Carburetors")
```
