---
title: "Chapter 4.1"
author: "rwr"
output: 
  html_document:
    df_print: paged
---

```{r library, include=FALSE}
library(tidyverse)
```


```{r}
winniweather <- read_csv("winniweather-orig.csv", col_types = "iiicdiiid")
```


```{r}
winniweather <- 
  winniweather %>%
  mutate(yearmonth = paste(year, month, sep = "-")) %>%
  select(yearmonth, everything(), -year, -month) %>%
  filter(time %in% c("00:00", "06:00", "12:00", "18:00")) %>%
  select(-rh_pct, -wd, -ws, -stn_p) %>%
  spread(time, temp_c) %>%
  rename(
    temp00_00 = `00:00`,
    temp06_00 = `06:00`,
    temp12_00 = `12:00`,
    temp18_00 = `18:00`)
```


```{r, paged.print=FALSE}
winniweather
```


```{r, paged.print=FALSE}
winniweather <- winniweather %>%
  gather(key = hour, value = temp, starts_with("temp"))

winniweather
```


```{r, paged.print=FALSE}
winniweather <- winniweather %>%
  mutate(hour = case_when(
    hour == "temp00_00" ~ 0L,
    hour == "temp06_00" ~ 6L,
    hour == "temp12_00" ~ 12L,
    hour == "temp18_00" ~ 18L))

winniweather
```


```{r, paged.print=FALSE}
winniweather <- winniweather %>%
  separate(yearmonth, c("year", "month"), sep = "-", convert = TRUE)

winniweather
```


```{r, paged.print=FALSE}
winniweather <- winniweather %>%
  arrange(year, month, day)

winniweather
```


```{r, paged.print=FALSE}
winniweather_iso <- winniweather %>%
  mutate(iso_date = ISOdate(year, month, day, hour))

winniweather_iso
```


```{r}
ggplot(data = winniweather_iso) +
  geom_point(mapping = aes(x = iso_date, y = temp))
```
