---
title: "Chapter 2.1"
author: "rwr"
output: 
  html_document:
    df_print: paged
---

```{r load_tidyverse}
library(tidyverse)
```


## filter: Picking Observations by their Values

```{r filter_droid}
filter(starwars, species == "Droid")
```


```{r filter_height_gt_220}
filter(starwars, height > 220)
```


```{r starwars_height_mass}
# Filter characters by either `height` above 210, or, `mass` above 120
filter(starwars, height > 210 | mass > 120)
```


```{r starwars_species_or}
# Get all Droid and Human characters; method 1 with [expr | expr]
filter(starwars, species == "Droid" | species == "Human")
```


```{r starwars_species_in}
# Get all Droid and Human characters; method 2 with [colname %in% c(...)]
filter(starwars, species %in% c("Droid", "Human"))
```


```{r starwars_arrange_height}
# Arrange characters by increasing height
arrange(starwars, height)
```


```{r starwars_arrange_twice}
# Arrange characters by hair color and then by skin color
arrange(starwars, hair_color, skin_color)
```


```{r starwars_arrange_desc}
# Arrange by descending `hair_color`, then by ascending `skin_color`
arrange(starwars, desc(hair_color), skin_color)
```


## select: Picking Variables by their Names

```{r starwars_select}
# Select the `name`, `gender`, and `species` columns
select(starwars, name, gender, species)
```


```{r starwars_select_revised}
# Select the `gender`, `species`, and `name` columns; in that order
select(starwars, gender, species, name)
```


```{r starwars_select_ends_with}
# Select `name` and all columns ending with "color" 
select(starwars, name, ends_with("color"))
```


```{r starwars_select_contains}
# Select `name` and all other columns containing a `_` character 
select(starwars, name, contains("_"))
```


```{r starwars_select_w_everything}
# Put 3 specific columns first then everything else after that 
select(starwars, name, homeworld, gender, everything())
```


## mutate: Creating New Variables with Expressions

```{r make_starwars_small}
# Create the `starwars_small` table, containing just 3 columns
starwars_small <- select(starwars, name, height, mass)
starwars_small
```


```{r mutate_bmi}
# Add the `bmi` column containing a calculation based
# on `height` and `mass` (with units of kg/m^2)
mutate(starwars_small, bmi = mass / (height / 100)^2)
```


```{r mutate_bmi_round}
# Add the `bmi` column as before and then create `bmi_rnd`
mutate(
  starwars_small,
  bmi = mass / (height / 100)^2,
  bmi_rnd = round(bmi, 0))
```


## summarize: Collapsing Many Values Down to a Single Summary

```{r group_by_summarize_mean}
# Create grouped data; where the table is grouped by `species`
by_species <- group_by(starwars, species)

# Create a data summary that gets the mean mass by `species`
summarize(by_species, avg_mass = mean(mass))
```


```{r group_by_summarize_mean_na_rm}
# Create grouped data; where the table is grouped by `species`
by_species <- group_by(starwars, species)

# Summarize with means, removing NA values
summarize(by_species, avg_mass = mean(mass, na.rm = TRUE))
```


```{r starwars_summarize_two_column_groups}
# Create grouped data; grouping by `species` and `gender`
grouping <- group_by(starwars, species, gender)

# Summarize to get average mass and average height
summarize(
  grouping,
  avg_mass = mean(mass, na.rm = TRUE),
  avg_height = mean(height, na.rm = TRUE))
```


## Bringing All of This Together with the Pipe (%>%)

```{r dplyr_stmts}
# Get average BMI values for humans across the different worlds

humans <- filter(starwars, species == "Human")

humans_bmi <- mutate(humans, bmi = mass / (height / 100)^2)

humans_bmi_by_homeworld <- group_by(humans_bmi, homeworld)

humans_avg_bmi_by_homeworld <- 
  summarize(humans_bmi_by_homeworld, avg_bmi = mean(bmi, na.rm = TRUE))

humans_avg_bmi_by_homeworld_sorted <-
  arrange(humans_avg_bmi_by_homeworld, desc(avg_bmi))

humans_avg_bmi_by_homeworld_sorted
```


```{r dplyr_piped}
# Get a table of average BMI values for humans across
# the different worlds in a single, piped expression
bmi_sorted <- starwars %>%
  filter(species == "Human") %>%
  mutate(bmi = mass / (height / 100)^2) %>%
  group_by(homeworld) %>%
  summarize(avg_bmi = mean(bmi, na.rm = TRUE)) %>%
  arrange(desc(avg_bmi))

bmi_sorted
```

